// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// circular_asd
long long circular_asd(NumericMatrix X, NumericVector x);
RcppExport SEXP _simplicialdepth_circular_asd(SEXP XSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(circular_asd(X, x));
    return rcpp_result_gen;
END_RCPP
}
// circular_asd_all_points
DataFrame circular_asd_all_points(NumericMatrix points_mat);
RcppExport SEXP _simplicialdepth_circular_asd_all_points(SEXP points_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type points_mat(points_matSEXP);
    rcpp_result_gen = Rcpp::wrap(circular_asd_all_points(points_mat));
    return rcpp_result_gen;
END_RCPP
}
// SDk
long long SDk(NumericMatrix Xinput_mat, NumericVector x_vec, int k);
RcppExport SEXP _simplicialdepth_SDk(SEXP Xinput_matSEXP, SEXP x_vecSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Xinput_mat(Xinput_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vec(x_vecSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(SDk(Xinput_mat, x_vec, k));
    return rcpp_result_gen;
END_RCPP
}
// SDk_parallel
long long SDk_parallel(NumericMatrix Xinput_mat, NumericVector x_vec, int k);
RcppExport SEXP _simplicialdepth_SDk_parallel(SEXP Xinput_matSEXP, SEXP x_vecSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Xinput_mat(Xinput_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vec(x_vecSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(SDk_parallel(Xinput_mat, x_vec, k));
    return rcpp_result_gen;
END_RCPP
}
// SDk_parallel_threads
long long SDk_parallel_threads(NumericMatrix Xinput_mat, NumericVector x_vec, int k, int threads);
RcppExport SEXP _simplicialdepth_SDk_parallel_threads(SEXP Xinput_matSEXP, SEXP x_vecSEXP, SEXP kSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Xinput_mat(Xinput_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vec(x_vecSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(SDk_parallel_threads(Xinput_mat, x_vec, k, threads));
    return rcpp_result_gen;
END_RCPP
}
// SDk_all_points
NumericVector SDk_all_points(NumericMatrix Xinput_mat, int k, int threads);
RcppExport SEXP _simplicialdepth_SDk_all_points(SEXP Xinput_matSEXP, SEXP kSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Xinput_mat(Xinput_matSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(SDk_all_points(Xinput_mat, k, threads));
    return rcpp_result_gen;
END_RCPP
}
// simplicial_depth_2d
long long simplicial_depth_2d(NumericMatrix points_mat, NumericVector q_vec);
RcppExport SEXP _simplicialdepth_simplicial_depth_2d(SEXP points_matSEXP, SEXP q_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type points_mat(points_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q_vec(q_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(simplicial_depth_2d(points_mat, q_vec));
    return rcpp_result_gen;
END_RCPP
}
// simplicial_depth_3d
long long simplicial_depth_3d(NumericMatrix X, NumericVector q, int threads);
RcppExport SEXP _simplicialdepth_simplicial_depth_3d(SEXP XSEXP, SEXP qSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(simplicial_depth_3d(X, q, threads));
    return rcpp_result_gen;
END_RCPP
}
// spherical_asd
long long spherical_asd(NumericMatrix X, NumericVector ray);
RcppExport SEXP _simplicialdepth_spherical_asd(SEXP XSEXP, SEXP raySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ray(raySEXP);
    rcpp_result_gen = Rcpp::wrap(spherical_asd(X, ray));
    return rcpp_result_gen;
END_RCPP
}
// spherical_asd_all_points
NumericVector spherical_asd_all_points(NumericMatrix X, int threads);
RcppExport SEXP _simplicialdepth_spherical_asd_all_points(SEXP XSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(spherical_asd_all_points(X, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_simplicialdepth_circular_asd", (DL_FUNC) &_simplicialdepth_circular_asd, 2},
    {"_simplicialdepth_circular_asd_all_points", (DL_FUNC) &_simplicialdepth_circular_asd_all_points, 1},
    {"_simplicialdepth_SDk", (DL_FUNC) &_simplicialdepth_SDk, 3},
    {"_simplicialdepth_SDk_parallel", (DL_FUNC) &_simplicialdepth_SDk_parallel, 3},
    {"_simplicialdepth_SDk_parallel_threads", (DL_FUNC) &_simplicialdepth_SDk_parallel_threads, 4},
    {"_simplicialdepth_SDk_all_points", (DL_FUNC) &_simplicialdepth_SDk_all_points, 3},
    {"_simplicialdepth_simplicial_depth_2d", (DL_FUNC) &_simplicialdepth_simplicial_depth_2d, 2},
    {"_simplicialdepth_simplicial_depth_3d", (DL_FUNC) &_simplicialdepth_simplicial_depth_3d, 3},
    {"_simplicialdepth_spherical_asd", (DL_FUNC) &_simplicialdepth_spherical_asd, 2},
    {"_simplicialdepth_spherical_asd_all_points", (DL_FUNC) &_simplicialdepth_spherical_asd_all_points, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_simplicialdepth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
