# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

circular_asd <- function(X, x) {
    .Call(`_simplicialdepth_circular_asd`, X, x)
}

circular_asd_all_arcs <- function(points_mat) {
    .Call(`_simplicialdepth_circular_asd_all_arcs`, points_mat)
}

SDk <- function(Xinput_mat, x_vec, k) {
    .Call(`_simplicialdepth_SDk`, Xinput_mat, x_vec, k)
}

SDk_parallel <- function(Xinput_mat, x_vec, k) {
    .Call(`_simplicialdepth_SDk_parallel`, Xinput_mat, x_vec, k)
}

SDk_parallel_threads <- function(Xinput_mat, x_vec, k, threads = 0L) {
    .Call(`_simplicialdepth_SDk_parallel_threads`, Xinput_mat, x_vec, k, threads)
}

SDk_all_points <- function(Xinput_mat, k, threads = 0L) {
    .Call(`_simplicialdepth_SDk_all_points`, Xinput_mat, k, threads)
}

simplicial_depth_2d <- function(points_mat, q_vec) {
    .Call(`_simplicialdepth_simplicial_depth_2d`, points_mat, q_vec)
}

simplicial_depth_3d <- function(X, q, threads = 0L) {
    .Call(`_simplicialdepth_simplicial_depth_3d`, X, q, threads)
}

spherical_asd <- function(X, ray) {
    .Call(`_simplicialdepth_spherical_asd`, X, ray)
}

spherical_asd_all_points <- function(X, threads = 0L) {
    .Call(`_simplicialdepth_spherical_asd_all_points`, X, threads)
}

